name: Build rust builders
on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * *'

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        builder_name:
          - rust-nostd-esp
          - rust-std-esp32
          - rust-std-esp32c3
          - rust-std-esp32s2
          - rust-std-esp32s3
          - rust-training-esp32c3
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        run: docker build -t "wokwi/builder-${BUILDER_NAME}" ${BUILDER_NAME}
        env:
          BUILDER_NAME: ${{ matrix.builder_name }}
