name: Build rust builders
on:
  workflow_dispatch:
  schedule:
    - cron: '37 13 * * *'

jobs:
  build:
    name: Build containers
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        builder_name:
          - rust-nostd-esp

    env:
      BUILDER_NAME: ${{ matrix.builder_name }}

    steps:
      - uses: actions/checkout@v4
      - name: Build container
        run: docker build -t "wokwi/builder-${BUILDER_NAME}" ${BUILDER_NAME}
